### ISSUE TITLE
Set up .gitignore  file

### ISSUE THREAD

**Issue by ycs1m1yk** [euphony-io/listen-my-order#1]
We need a .gitignore file.
Is it okay that set up gitignore by [gitignore.io](https://www.toptal.com/developers/gitignore) with Java, Kotlin, Android, AndroidStudio tag?

If need more, write it here. thx!

**Comment by HACore** [comment]
I think that will be enough. good!

**Comment by ycs1m1yk** [comment]
Done.

**Comment by hoho00** [comment]
I'm gonna comment about firebase api key. Maybe there are some adding files like .env.

**Comment by ycs1m1yk** [comment]
https://github.com/euphony-io/listen-my-order/issues/1#issuecomment-902458318

> I'm gonna comment about firebase api key. Maybe there are some adding files like .env.

Good point!
Maybe the following line shoud be added.
```
### dotenv ###
.env
```
