### ISSUE TITLE
Develop Rules

### ISSUE THREAD

**Issue by YoungSeokHong** [euphony-io/listen-my-order#10]
이 앱을 개발하면서 코드와 커밋 등 개발방식에 있어서 통일성에 대해 의논할 필요가 있다고 생각해서 만들게 됐습니다.

**Comment by YoungSeokHong** [comment]
가장 기본적인 것으로 먼저 layout 속에 들어가는 widget ID 명명 방식에 대해 의논해볼 필요가 있을 것 같습니다.

1.  Widget들의 Id를 정할 때 "(위젯 명)_(위젯 종류)" (예. import_menu_button)과 같은 방식으로 할지 "(위젯 종류)_(위젯 명)" (예. button_import_menu)과 같은 방식으로 할지를 정해야 할 것 같습니다.

2. 추가적으로 저는 button이나 text view, edit text와 같은 위젯들에 대해서 종류를 적을 때 btn, tv, et 와 같이 약자를 사용하고 싶은데 다른 분들은 어떤 의견들을 갖고 계신지 듣고싶습니다!

**Comment by ycs1m1yk** [comment]
> 가장 기본적인 것으로 먼저 layout 속에 들어가는 widget ID 명명 방식에 대해 의논해볼 필요가 있을 것 같습니다.
> 
> 1. Widget들의 Id를 정할 때 "(위젯 명)_(위젯 종류)" (예. import_menu_button)과 같은 방식으로 할지 "(위젯 종류)_(위젯 명)" (예. button_import_menu)과 같은 방식으로 할지를 정해야 할 것 같습니다.
> 2. 추가적으로 저는 button이나 text view, edit text와 같은 위젯들에 대해서 종류를 적을 때 btn, tv, et 와 같이 약자를 사용하고 싶은데 다른 분들은 어떤 의견들을 갖고 계신지 듣고싶습니다!

필요한 논의라고 생각합니다! 🙌🙌 
검색을 해보니 이 레포지토리가 참고하기 좋은 것 같습니다. [ribot/android-guidelines](https://github.com/ribot/android-guidelines) 
코드 가이드라인에 관한 문서입니다. [project_and_code_guidelines](https://github.com/ribot/android-guidelines/blob/master/project_and_code_guidelines.md) 

# 긁어온 예시
#### 1.2.2.1 Drawable files

Naming conventions for drawables:


| Asset Type   | Prefix            |		Example               |
|--------------| ------------------|-----------------------------|
| Action bar   | `ab_`             | `ab_stacked.9.png`          |
| Button       | `btn_`	            | `btn_send_pressed.9.png`    |
| Dialog       | `dialog_`         | `dialog_top.9.png`          |
| Divider      | `divider_`        | `divider_horizontal.9.png`  |
| Icon         | `ic_`	            | `ic_star.png`               |
| Menu         | `menu_	`           | `menu_submenu_bg.9.png`     |
| Notification | `notification_`	| `notification_bg.9.png`     |
| Tabs         | `tab_`            | `tab_pressed.9.png`         |

Naming conventions for icons (taken from [Android iconography guidelines](http://developer.android.com/design/style/iconography.html)):

| Asset Type                      | Prefix             | Example                      |
| --------------------------------| ----------------   | ---------------------------- |
| Icons                           | `ic_`              | `ic_star.png`                |
| Launcher icons                  | `ic_launcher`      | `ic_launcher_calendar.png`   |
| Menu icons and Action Bar icons | `ic_menu`          | `ic_menu_archive.png`        |
| Status bar icons                | `ic_stat_notify`   | `ic_stat_notify_msg.png`     |
| Tab icons                       | `ic_tab`           | `ic_tab_recent.png`          |
| Dialog icons                    | `ic_dialog`        | `ic_dialog_info.png`         |

Naming conventions for selector states:

| State	       | Suffix          | Example                     |
|--------------|-----------------|-----------------------------|
| Normal       | `_normal`       | `btn_order_normal.9.png`    |
| Pressed      | `_pressed`      | `btn_order_pressed.9.png`   |
| Focused      | `_focused`      | `btn_order_focused.9.png`   |
| Disabled     | `_disabled`     | `btn_order_disabled.9.png`  |
| Selected     | `_selected`     | `btn_order_selected.9.png`  |

**Comment by hoho00** [comment]
오 몰랐네요. 저는 영석님이 처음에 적어 주신 import_menu_button 이런식으로 view id를 결정했는데, 규칙을 정할 필요가 있어 보입니다.

**Comment by YoungSeokHong** [comment]
그러면
1. "(위젯 명)(위젯 종류)" (예. import_menu_button)로 하시려면 "Laugh" 이모티콘을
2. ""(위젯 종류)(위젯 명)" (예. button_import_menu)으로 하시려면 "Hooray"이모티콘을 눌러주세요.
그리고 위젯 종류와 파일명 같은건 혜성님께서 올려주신 정보같이 약어 쓰기 + 저 표에 없는 내용들은 대문자만 추려서 소문자로 적어서(ex. Edit Text -> et / Text View -> tv / Recycler View -> rc)하는 건 어떨까요?

**Comment by HACore** [comment]
> 그리고 위젯 종류와 파일명 같은건 혜성님께서 올려주신 정보같이 약어 쓰기 + 저 표에 없는 내용들은 대문자만 추려서 소문자로 적어서(ex. Edit Text -> et / Text View -> tv / Recycler View -> rc)하는 건 어떨까요?

좋습니다! 가독성 측면에서 약어로 적는게 더 좋을 듯 싶어요 :)
**Recycler View -> rc**는 **rv** 말씀하신거 맞을까요?

**Comment by YoungSeokHong** [comment]
> 좋습니다! 가독성 측면에서 약어로 적는게 더 좋을 듯 싶어요 :)
> **Recycler View -> rc**는 **rv** 말씀하신거 맞을까요?

앗! 네넵 오타났네요 ㅠㅠ 하은님 말씀하신게 맞습니다!

**Comment by hoho00** [comment]
view id 는 그러면 약어_기능 이런식으로 가나요?
ex) btn_import_menu

**Comment by ycs1m1yk** [comment]
> view id 는 그러면 약어_기능 이런식으로 가나요?
> ex) btn_import_menu

넵 저는 이렇게 이해했습니다.

**Comment by YoungSeokHong** [comment]
> view id 는 그러면 약어_기능 이런식으로 가나요?
> ex) btn_import_menu

네 맞습니다!

**Comment by hoho00** [comment]
네 이후에 고려해서 리팩토링 진행하겠습니다
