### ISSUE TITLE
CODEOWNERS apply

### ISSUE THREAD

**Issue by ycs1m1yk** [euphony-io/listen-my-order#3]
Let's define code owners!
reference is here: [About code owners](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners)

**Comment by ycs1m1yk** [comment]
I think CODEOWNERS file
to be:
```
* @euphony-io/euphony-co 
```
located root directory.

Tell me your opinions!

**Comment by HACore** [comment]
Team code owner is guided in the reference [(About code owners)](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners) as follows:

> When the code owner is a team, that team must have explicit `write` permissions, even if all the individual members of the team already have `write` permissions directly, through organization membership.

Is it okay that setting CODEOWNERS to euphony-co team? I think we have to be sure.

**Comment by ycs1m1yk** [comment]
> Team code owner is guided in the reference [(About code owners)](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners) as follows:
> 
> > When the code owner is a team, that team must have explicit `write` permissions, even if all the individual members of the team already have `write` permissions directly, through organization membership.
> 
> Is it okay that setting CODEOWNERS to euphony-co team? I think we have to be sure.

That's a good point! I granted write permission of this repository to euphony-co team. 


### How i granted write permissions
1. In euphony-io/listen-my-order page, go to ***Settings > Manage access***
<img src="https://user-images.githubusercontent.com/27720475/130009759-754101c6-a760-4148-b0f6-c993b66cea96.png" width="100%" height="100%">

2. Invite euphony-co team and give maintain role
![image](https://user-images.githubusercontent.com/27720475/130009957-96e14b7d-ddd0-4a0f-8cfb-0e53951f0926.png)

  Maintain role description is below:

<img src="https://user-images.githubusercontent.com/27720475/130010037-eb2887af-4e40-4743-b733-bd67f0120910.png" width="40%" heig
ht="40%">
