### ISSUE TITLE
Old version update in develop branch

### ISSUE THREAD

**Issue by HACore** [euphony-io/listen-my-order#36]
현재 develop 브랜치에 마지막으로 merge된 커밋(161bd53)이 옛날 폴더 구조의 파일들을 모두 가져온 것 같습니다.
이로 인해 각 액티비티의 내용도 옛날 버전으로 바뀌었고 제가 머지하려는 커밋과 충돌도 상당수 일어나고 있네요..

@ycs1m1yk 
혹시 이번 merge 작업으로 develop 브랜치에서 업데이트 해야할 부분이 뭐였을까요?
해당 작업내용이 다른 브랜치에 남아있거나 수정할 부분이 적다면 161bd53 커밋을 취소하고 필요한 부분만 살려서 다시 merge하는것이 나을 거 같습니다!

**Comment by ycs1m1yk** [comment]
> 현재 develop 브랜치에 마지막으로 merge된 커밋([161bd53](https://github.com/euphony-io/listen-my-order/commit/161bd532c1d619aa76eb4c90a6ce6fd3d4e71db7))이 옛날 폴더 구조의 파일들을 모두 가져온 것 같습니다.
> 이로 인해 각 액티비티의 내용도 옛날 버전으로 바뀌었고 제가 머지하려는 커밋과 충돌도 상당수 일어나고 있네요..
> 
> @ycs1m1yk
> 혹시 이번 merge 작업으로 develop 브랜치에서 업데이트 해야할 부분이 뭐였을까요?
> 해당 작업내용이 다른 브랜치에 남아있거나 수정할 부분이 적다면 [161bd53](https://github.com/euphony-io/listen-my-order/commit/161bd532c1d619aa76eb4c90a6ce6fd3d4e71db7) 커밋을 취소하고 필요한 부분만 살려서 다시 merge하는것이 나을 거 같습니다!

헉 죄송합니다 머지 실수했네요ㅜㅜ
돌려놓겠습니다

**Comment by HACore** [comment]
감사합니다 :)
